const FLIGHT_SCENARIOS = [
  {
    id: 'DOM-OW-ECO-1', label: 'Domestic OW Economy | BOM→DEL | 1 Adult',
    type: 'domestic', tripType: 'one-way',
    from: 'BOM', fromCity: 'Mumbai',
    to: 'DEL', toCity: 'Delhi',
    cabinClass: 'Economy',
    passengers: { adults: 1, children: 0, infants: 0 },
    dateOffsetDays: 7,
    filtersToApply: ['sort_by_price'],
    preferNonStop: true,
  },
  {
    id: 'DOM-OW-BIZ-2', label: 'Domestic OW Business | DEL→BLR | 2 Adults',
    type: 'domestic', tripType: 'one-way',
    from: 'DEL', fromCity: 'Delhi',
    to: 'BLR', toCity: 'Bangalore',
    cabinClass: 'Business',
    passengers: { adults: 2, children: 0, infants: 0 },
    dateOffsetDays: 14,
    filtersToApply: ['business_only'],
    preferNonStop: false,
  },
  {
    id: 'DOM-RT-ECO-3', label: 'Domestic RT Economy | AMD→BOM | 1 Adult 1 Child',
    type: 'domestic', tripType: 'round-trip',
    from: 'AMD', fromCity: 'Ahmedabad',
    to: 'BOM', toCity: 'Mumbai',
    cabinClass: 'Economy',
    passengers: { adults: 1, children: 1, infants: 0 },
    dateOffsetDays: 10, returnOffsetDays: 14,
    filtersToApply: ['sort_by_price', 'morning_flights'],
    preferNonStop: true,
  },
  {
    id: 'DOM-OW-ECO-4', label: 'Domestic OW Economy | BLR→CCU | 3 Adults 1 Infant',
    type: 'domestic', tripType: 'one-way',
    from: 'BLR', fromCity: 'Bangalore',
    to: 'CCU', toCity: 'Kolkata',
    cabinClass: 'Economy',
    passengers: { adults: 3, children: 0, infants: 1 },
    dateOffsetDays: 5,
    filtersToApply: ['sort_by_duration'],
    preferNonStop: false,
  },
  {
    id: 'DOM-OW-ECO-5', label: 'Domestic OW Economy | MAA→HYD | 4 Adults',
    type: 'domestic', tripType: 'one-way',
    from: 'MAA', fromCity: 'Chennai',
    to: 'HYD', toCity: 'Hyderabad',
    cabinClass: 'Economy',
    passengers: { adults: 4, children: 0, infants: 0 },
    dateOffsetDays: 3,
    filtersToApply: ['sort_by_price'],
    preferNonStop: true,
  },
  {
    id: 'DOM-RT-BIZ-6', label: 'Domestic RT Business | BOM→GOI | 2 Adults',
    type: 'domestic', tripType: 'round-trip',
    from: 'BOM', fromCity: 'Mumbai',
    to: 'GOI', toCity: 'Goa',
    cabinClass: 'Business',
    passengers: { adults: 2, children: 0, infants: 0 },
    dateOffsetDays: 20, returnOffsetDays: 25,
    filtersToApply: ['business_only'],
    preferNonStop: true,
  },
  {
    id: 'INTL-OW-ECO-1', label: 'International OW Economy | BOM→DXB | 2 Adults',
    type: 'international', tripType: 'one-way',
    from: 'BOM', fromCity: 'Mumbai',
    to: 'DXB', toCity: 'Dubai',
    cabinClass: 'Economy',
    passengers: { adults: 2, children: 0, infants: 0 },
    dateOffsetDays: 21,
    filtersToApply: ['sort_by_price', 'nonstop_only'],
    preferNonStop: true,
  },
  {
    id: 'INTL-RT-ECO-2', label: 'International RT Economy | DEL→SIN | 1 Adult 1 Child',
    type: 'international', tripType: 'round-trip',
    from: 'DEL', fromCity: 'Delhi',
    to: 'SIN', toCity: 'Singapore',
    cabinClass: 'Economy',
    passengers: { adults: 1, children: 1, infants: 0 },
    dateOffsetDays: 30, returnOffsetDays: 37,
    filtersToApply: ['sort_by_price', 'airline_filter_indigo'],
    preferNonStop: false,
  },
  {
    id: 'INTL-OW-BIZ-3', label: 'International OW Business | BOM→LHR | 1 Adult',
    type: 'international', tripType: 'one-way',
    from: 'BOM', fromCity: 'Mumbai',
    to: 'LHR', toCity: 'London',
    cabinClass: 'Business',
    passengers: { adults: 1, children: 0, infants: 0 },
    dateOffsetDays: 45,
    filtersToApply: ['business_only'],
    preferNonStop: false,
  },
  {
    id: 'INTL-RT-ECO-4', label: 'International RT Economy | BLR→BKK | 2A 1C 1I',
    type: 'international', tripType: 'round-trip',
    from: 'BLR', fromCity: 'Bangalore',
    to: 'BKK', toCity: 'Bangkok',
    cabinClass: 'Economy',
    passengers: { adults: 2, children: 1, infants: 1 },
    dateOffsetDays: 15, returnOffsetDays: 22,
    filtersToApply: ['sort_by_price'],
    preferNonStop: false,
  },
  {
    id: 'INTL-OW-ECO-5', label: 'International OW Economy | DEL→KUL | 5 Adults',
    type: 'international', tripType: 'one-way',
    from: 'DEL', fromCity: 'Delhi',
    to: 'KUL', toCity: 'Kuala Lumpur',
    cabinClass: 'Economy',
    passengers: { adults: 5, children: 0, infants: 0 },
    dateOffsetDays: 12,
    filtersToApply: ['sort_by_price'],
    preferNonStop: false,
  },
  {
    id: 'INTL-RT-BIZ-6', label: 'International RT Business | BOM→JFK | 2 Adults',
    type: 'international', tripType: 'round-trip',
    from: 'BOM', fromCity: 'Mumbai',
    to: 'JFK', toCity: 'New York',
    cabinClass: 'Business',
    passengers: { adults: 2, children: 0, infants: 0 },
    dateOffsetDays: 60, returnOffsetDays: 67,
    filtersToApply: ['business_only', 'airline_filter'],
    preferNonStop: false,
  },
  {
    id: 'INTL-OW-ECO-7', label: 'International OW Economy | HYD→AUH | 3 Adults',
    type: 'international', tripType: 'one-way',
    from: 'HYD', fromCity: 'Hyderabad',
    to: 'AUH', toCity: 'Abu Dhabi',
    cabinClass: 'Economy',
    passengers: { adults: 3, children: 0, infants: 0 },
    dateOffsetDays: 9,
    filtersToApply: ['nonstop_only'],
    preferNonStop: true,
  },
];

module.exports = { FLIGHT_SCENARIOS };
