const HOTEL_SCENARIOS = [
  {
    id: 'HTL-DOM-1', label: 'Domestic | Goa | 2 Adults | 1 Room | 3N | 3★',
    type: 'domestic', destination: 'Goa', destinationCode: 'GOI',
    checkinOffsetDays: 10, nights: 3,
    rooms: 1, adultsPerRoom: 2, childrenPerRoom: 0,
    starFilter: '3',
    filtersToApply: ['sort_by_price', 'free_cancellation'],
    preferRoomType: 'Deluxe Room',
  },
  {
    id: 'HTL-DOM-2', label: 'Domestic | Mumbai | 1 Adult | 1 Room | 1N | 5★',
    type: 'domestic', destination: 'Mumbai', destinationCode: 'BOM',
    checkinOffsetDays: 7, nights: 1,
    rooms: 1, adultsPerRoom: 1, childrenPerRoom: 0,
    starFilter: '5',
    filtersToApply: ['5_star'],
    preferRoomType: 'Superior Room',
  },
  {
    id: 'HTL-DOM-3', label: 'Domestic | Delhi | 2A 1C | 2 Rooms | 2N | 4★',
    type: 'domestic', destination: 'New Delhi', destinationCode: 'DEL',
    checkinOffsetDays: 14, nights: 2,
    rooms: 2, adultsPerRoom: 2, childrenPerRoom: 1,
    starFilter: '4',
    filtersToApply: ['sort_by_rating'],
    preferRoomType: 'Family Room',
  },
  {
    id: 'HTL-DOM-4', label: 'Domestic | Jaipur | 4 Adults | 2 Rooms | 3N | 3★',
    type: 'domestic', destination: 'Jaipur', destinationCode: 'JAI',
    checkinOffsetDays: 5, nights: 3,
    rooms: 2, adultsPerRoom: 2, childrenPerRoom: 0,
    starFilter: '3',
    filtersToApply: ['sort_by_price'],
    preferRoomType: 'Standard Room',
  },
  {
    id: 'HTL-DOM-5', label: 'Domestic | Hyderabad | 2 Adults | 1 Room | 2N | 4★',
    type: 'domestic', destination: 'Hyderabad', destinationCode: 'HYD',
    checkinOffsetDays: 8, nights: 2,
    rooms: 1, adultsPerRoom: 2, childrenPerRoom: 0,
    starFilter: '4',
    filtersToApply: ['free_breakfast'],
    preferRoomType: 'Deluxe Room',
  },
  {
    id: 'HTL-INTL-1', label: 'International | Dubai | 2 Adults | 1 Room | 4N | 5★',
    type: 'international', destination: 'Dubai', destinationCode: 'DXB',
    checkinOffsetDays: 21, nights: 4,
    rooms: 1, adultsPerRoom: 2, childrenPerRoom: 0,
    starFilter: '5',
    filtersToApply: ['5_star', 'free_cancellation'],
    preferRoomType: 'Deluxe Room',
  },
  {
    id: 'HTL-INTL-2', label: 'International | Bangkok | 3A 2C | 2 Rooms | 5N | 4★',
    type: 'international', destination: 'Bangkok', destinationCode: 'BKK',
    checkinOffsetDays: 15, nights: 5,
    rooms: 2, adultsPerRoom: 2, childrenPerRoom: 1,
    starFilter: '4',
    filtersToApply: ['sort_by_rating'],
    preferRoomType: 'Family Room',
  },
  {
    id: 'HTL-INTL-3', label: 'International | Singapore | 2 Adults | 1 Room | 3N | 5★',
    type: 'international', destination: 'Singapore', destinationCode: 'SIN',
    checkinOffsetDays: 30, nights: 3,
    rooms: 1, adultsPerRoom: 2, childrenPerRoom: 0,
    starFilter: '5',
    filtersToApply: ['5_star'],
    preferRoomType: 'Premier Room',
  },
  {
    id: 'HTL-INTL-4', label: 'International | Bali | 2 Adults | 1 Room | 7N | 4★',
    type: 'international', destination: 'Bali', destinationCode: 'DPS',
    checkinOffsetDays: 20, nights: 7,
    rooms: 1, adultsPerRoom: 2, childrenPerRoom: 0,
    starFilter: '4',
    filtersToApply: ['free_breakfast', 'free_cancellation'],
    preferRoomType: 'Pool Villa',
  },
  {
    id: 'HTL-INTL-5', label: 'International | Kuala Lumpur | 4 Adults | 2 Rooms | 3N | 3★',
    type: 'international', destination: 'Kuala Lumpur', destinationCode: 'KUL',
    checkinOffsetDays: 12, nights: 3,
    rooms: 2, adultsPerRoom: 2, childrenPerRoom: 0,
    starFilter: '3',
    filtersToApply: ['sort_by_price'],
    preferRoomType: 'Standard Room',
  },
  {
    id: 'HTL-INTL-6', label: 'International | London | 2 Adults | 1 Room | 6N | 4★',
    type: 'international', destination: 'London', destinationCode: 'LHR',
    checkinOffsetDays: 45, nights: 6,
    rooms: 1, adultsPerRoom: 2, childrenPerRoom: 0,
    starFilter: '4',
    filtersToApply: ['sort_by_rating'],
    preferRoomType: 'Executive Room',
  },
];

module.exports = { HOTEL_SCENARIOS };
