const INTERNATIONAL_DEEP_SCENARIOS = [
  // Middle East
  { id: 'INTL-DEEP-ME-01', label: 'Intl OW Economy | BOM→DXB | 2A | IndiGo filter', type: 'international', tripType: 'one-way', from: 'BOM', fromCity: 'Mumbai', to: 'DXB', toCity: 'Dubai', cabinClass: 'Economy', passengers: { adults: 2, children: 0, infants: 0 }, dateOffsetDays: 21, filtersToApply: ['nonstop_only', 'airline_filter_indigo'], preferNonStop: true, deepFocus: true },
  { id: 'INTL-DEEP-ME-02', label: 'Intl OW Business | DEL→AUH | 1A | Emirates', type: 'international', tripType: 'one-way', from: 'DEL', fromCity: 'Delhi', to: 'AUH', toCity: 'Abu Dhabi', cabinClass: 'Business', passengers: { adults: 1, children: 0, infants: 0 }, dateOffsetDays: 30, filtersToApply: ['business_only'], preferNonStop: false, deepFocus: true },
  { id: 'INTL-DEEP-ME-03', label: 'Intl OW Economy | HYD→KWI | 3A | Low fare', type: 'international', tripType: 'one-way', from: 'HYD', fromCity: 'Hyderabad', to: 'KWI', toCity: 'Kuwait', cabinClass: 'Economy', passengers: { adults: 3, children: 0, infants: 0 }, dateOffsetDays: 14, filtersToApply: ['sort_by_price'], preferNonStop: false, deepFocus: true },
  { id: 'INTL-DEEP-ME-04', label: 'Intl OW Economy | COK→DXB | 4A | Kerala-Gulf', type: 'international', tripType: 'one-way', from: 'COK', fromCity: 'Kochi', to: 'DXB', toCity: 'Dubai', cabinClass: 'Economy', passengers: { adults: 4, children: 0, infants: 0 }, dateOffsetDays: 10, filtersToApply: ['sort_by_price', 'nonstop_only'], preferNonStop: true, deepFocus: true },

  // Southeast Asia
  { id: 'INTL-DEEP-SEA-01', label: 'Intl OW Economy | BOM→SIN | 2A 1C | 1 stop', type: 'international', tripType: 'one-way', from: 'BOM', fromCity: 'Mumbai', to: 'SIN', toCity: 'Singapore', cabinClass: 'Economy', passengers: { adults: 2, children: 1, infants: 0 }, dateOffsetDays: 25, filtersToApply: ['sort_by_price'], preferNonStop: false, deepFocus: true },
  { id: 'INTL-DEEP-SEA-02', label: 'Intl OW Economy | DEL→BKK | 2A | Thai filter', type: 'international', tripType: 'one-way', from: 'DEL', fromCity: 'Delhi', to: 'BKK', toCity: 'Bangkok', cabinClass: 'Economy', passengers: { adults: 2, children: 0, infants: 0 }, dateOffsetDays: 18, filtersToApply: ['sort_by_price'], preferNonStop: false, deepFocus: true },
  { id: 'INTL-DEEP-SEA-03', label: 'Intl OW Economy | BLR→KUL | 5A | Group', type: 'international', tripType: 'one-way', from: 'BLR', fromCity: 'Bangalore', to: 'KUL', toCity: 'Kuala Lumpur', cabinClass: 'Economy', passengers: { adults: 5, children: 0, infants: 0 }, dateOffsetDays: 20, filtersToApply: ['sort_by_price'], preferNonStop: false, deepFocus: true },
  { id: 'INTL-DEEP-SEA-04', label: 'Intl OW Economy | MAA→DPS | 2A | Bali', type: 'international', tripType: 'one-way', from: 'MAA', fromCity: 'Chennai', to: 'DPS', toCity: 'Bali', cabinClass: 'Economy', passengers: { adults: 2, children: 0, infants: 0 }, dateOffsetDays: 30, filtersToApply: ['sort_by_price'], preferNonStop: false, deepFocus: true },

  // Europe
  { id: 'INTL-DEEP-EU-01', label: 'Intl OW Economy | BOM→LHR | 2A | Air India', type: 'international', tripType: 'one-way', from: 'BOM', fromCity: 'Mumbai', to: 'LHR', toCity: 'London', cabinClass: 'Economy', passengers: { adults: 2, children: 0, infants: 0 }, dateOffsetDays: 45, filtersToApply: ['sort_by_price'], preferNonStop: false, deepFocus: true },
  { id: 'INTL-DEEP-EU-02', label: 'Intl OW Business | DEL→CDG | 1A | Paris', type: 'international', tripType: 'one-way', from: 'DEL', fromCity: 'Delhi', to: 'CDG', toCity: 'Paris', cabinClass: 'Business', passengers: { adults: 1, children: 0, infants: 0 }, dateOffsetDays: 60, filtersToApply: ['business_only'], preferNonStop: false, deepFocus: true },

  // Long Haul
  { id: 'INTL-DEEP-LH-01', label: 'Intl OW Economy | BOM→SYD | 2A | Australia', type: 'international', tripType: 'one-way', from: 'BOM', fromCity: 'Mumbai', to: 'SYD', toCity: 'Sydney', cabinClass: 'Economy', passengers: { adults: 2, children: 0, infants: 0 }, dateOffsetDays: 45, filtersToApply: ['sort_by_price'], preferNonStop: false, deepFocus: true },
  { id: 'INTL-DEEP-LH-02', label: 'Intl OW Economy | DEL→YYZ | 2A | Canada', type: 'international', tripType: 'one-way', from: 'DEL', fromCity: 'Delhi', to: 'YYZ', toCity: 'Toronto', cabinClass: 'Economy', passengers: { adults: 2, children: 0, infants: 0 }, dateOffsetDays: 50, filtersToApply: ['sort_by_price'], preferNonStop: false, deepFocus: true },
];

const INTERNATIONAL_WEIGHT_BOOST = 1.5;

// CEO 2026-06-02: priority Flight INTL sectors that should be picked MORE often.
// Used by pulsePicker — 75% of INTL flight picks come from this list, 25% from
// the existing L2B + DEEP pool (so other routes still rotate occasionally).
const INTL_PRIORITY_SECTORS = [
  { id: 'INTL-PRIO-01', label: 'Priority | BOM→KWI | Kuwait City', from: 'BOM', fromCity: 'Mumbai', to: 'KWI', toCity: 'Kuwait City', type: 'international', cabinClass: 'Economy', passengers: { adults: 1 }, dateOffsetDays: 14, priority: 'HIGH', deepFocus: true },
  { id: 'INTL-PRIO-02', label: 'Priority | DEL→KWI | Kuwait City', from: 'DEL', fromCity: 'Delhi', to: 'KWI', toCity: 'Kuwait City', type: 'international', cabinClass: 'Economy', passengers: { adults: 1 }, dateOffsetDays: 21, priority: 'HIGH', deepFocus: true },
  { id: 'INTL-PRIO-03', label: 'Priority | DEL→DXB | Dubai', from: 'DEL', fromCity: 'Delhi', to: 'DXB', toCity: 'Dubai', type: 'international', cabinClass: 'Economy', passengers: { adults: 1 }, dateOffsetDays: 28, priority: 'HIGH', deepFocus: true },
  { id: 'INTL-PRIO-04', label: 'Priority | BOM→DXB | Dubai', from: 'BOM', fromCity: 'Mumbai', to: 'DXB', toCity: 'Dubai', type: 'international', cabinClass: 'Economy', passengers: { adults: 1 }, dateOffsetDays: 35, priority: 'HIGH', deepFocus: true },
  { id: 'INTL-PRIO-05', label: 'Priority | AMD→KWI | Kuwait City', from: 'AMD', fromCity: 'Ahmedabad', to: 'KWI', toCity: 'Kuwait City', type: 'international', cabinClass: 'Economy', passengers: { adults: 1 }, dateOffsetDays: 45, priority: 'HIGH', deepFocus: true },
  { id: 'INTL-PRIO-06', label: 'Priority | PNQ→BKK | Bangkok', from: 'PNQ', fromCity: 'Pune', to: 'BKK', toCity: 'Bangkok', type: 'international', cabinClass: 'Economy', passengers: { adults: 1 }, dateOffsetDays: 14, priority: 'HIGH', deepFocus: true },
  { id: 'INTL-PRIO-07', label: 'Priority | DEL→AUH | Abu Dhabi', from: 'DEL', fromCity: 'Delhi', to: 'AUH', toCity: 'Abu Dhabi', type: 'international', cabinClass: 'Economy', passengers: { adults: 1 }, dateOffsetDays: 21, priority: 'HIGH', deepFocus: true },
  { id: 'INTL-PRIO-08', label: 'Priority | DEL→SHJ | Sharjah', from: 'DEL', fromCity: 'Delhi', to: 'SHJ', toCity: 'Sharjah', type: 'international', cabinClass: 'Economy', passengers: { adults: 1 }, dateOffsetDays: 28, priority: 'HIGH', deepFocus: true },
  { id: 'INTL-PRIO-09', label: 'Priority | KWI→DEL | Delhi', from: 'KWI', fromCity: 'Kuwait City', to: 'DEL', toCity: 'Delhi', type: 'international', cabinClass: 'Economy', passengers: { adults: 1 }, dateOffsetDays: 35, priority: 'HIGH', deepFocus: true },
  { id: 'INTL-PRIO-10', label: 'Priority | CCU→DXB | Dubai', from: 'CCU', fromCity: 'Kolkata', to: 'DXB', toCity: 'Dubai', type: 'international', cabinClass: 'Economy', passengers: { adults: 1 }, dateOffsetDays: 45, priority: 'HIGH', deepFocus: true },
  { id: 'INTL-PRIO-11', label: 'Priority | DXB→DEL | Delhi', from: 'DXB', fromCity: 'Dubai', to: 'DEL', toCity: 'Delhi', type: 'international', cabinClass: 'Economy', passengers: { adults: 1 }, dateOffsetDays: 14, priority: 'HIGH', deepFocus: true },
  { id: 'INTL-PRIO-12', label: 'Priority | LKO→DXB | Dubai', from: 'LKO', fromCity: 'Lucknow', to: 'DXB', toCity: 'Dubai', type: 'international', cabinClass: 'Economy', passengers: { adults: 1 }, dateOffsetDays: 21, priority: 'HIGH', deepFocus: true },
  { id: 'INTL-PRIO-13', label: 'Priority | DXB→BOM | Mumbai', from: 'DXB', fromCity: 'Dubai', to: 'BOM', toCity: 'Mumbai', type: 'international', cabinClass: 'Economy', passengers: { adults: 1 }, dateOffsetDays: 28, priority: 'HIGH', deepFocus: true },
  { id: 'INTL-PRIO-14', label: 'Priority | BOM→AUH | Abu Dhabi', from: 'BOM', fromCity: 'Mumbai', to: 'AUH', toCity: 'Abu Dhabi', type: 'international', cabinClass: 'Economy', passengers: { adults: 1 }, dateOffsetDays: 35, priority: 'HIGH', deepFocus: true },
  { id: 'INTL-PRIO-15', label: 'Priority | AMD→BKK | Bangkok', from: 'AMD', fromCity: 'Ahmedabad', to: 'BKK', toCity: 'Bangkok', type: 'international', cabinClass: 'Economy', passengers: { adults: 1 }, dateOffsetDays: 45, priority: 'HIGH', deepFocus: true },
  { id: 'INTL-PRIO-16', label: 'Priority | KWI→BOM | Mumbai', from: 'KWI', fromCity: 'Kuwait City', to: 'BOM', toCity: 'Mumbai', type: 'international', cabinClass: 'Economy', passengers: { adults: 1 }, dateOffsetDays: 14, priority: 'HIGH', deepFocus: true },
  { id: 'INTL-PRIO-17', label: 'Priority | DEL→YYZ | Toronto', from: 'DEL', fromCity: 'Delhi', to: 'YYZ', toCity: 'Toronto', type: 'international', cabinClass: 'Economy', passengers: { adults: 1 }, dateOffsetDays: 21, priority: 'HIGH', deepFocus: true },
  { id: 'INTL-PRIO-18', label: 'Priority | DEL→BKK | Bangkok', from: 'DEL', fromCity: 'Delhi', to: 'BKK', toCity: 'Bangkok', type: 'international', cabinClass: 'Economy', passengers: { adults: 1 }, dateOffsetDays: 28, priority: 'HIGH', deepFocus: true },
  { id: 'INTL-PRIO-19', label: 'Priority | AMD→DXB | Dubai', from: 'AMD', fromCity: 'Ahmedabad', to: 'DXB', toCity: 'Dubai', type: 'international', cabinClass: 'Economy', passengers: { adults: 1 }, dateOffsetDays: 35, priority: 'HIGH', deepFocus: true },
  { id: 'INTL-PRIO-20', label: 'Priority | BOM→BKK | Bangkok', from: 'BOM', fromCity: 'Mumbai', to: 'BKK', toCity: 'Bangkok', type: 'international', cabinClass: 'Economy', passengers: { adults: 1 }, dateOffsetDays: 45, priority: 'HIGH', deepFocus: true },
  { id: 'INTL-PRIO-21', label: 'Priority | CCU→KWI | Kuwait City', from: 'CCU', fromCity: 'Kolkata', to: 'KWI', toCity: 'Kuwait City', type: 'international', cabinClass: 'Economy', passengers: { adults: 1 }, dateOffsetDays: 14, priority: 'HIGH', deepFocus: true },
  { id: 'INTL-PRIO-22', label: 'Priority | DEL→SIN | Singapore', from: 'DEL', fromCity: 'Delhi', to: 'SIN', toCity: 'Singapore', type: 'international', cabinClass: 'Economy', passengers: { adults: 1 }, dateOffsetDays: 21, priority: 'HIGH', deepFocus: true },
  { id: 'INTL-PRIO-23', label: 'Priority | DEL→RUH | Riyadh', from: 'DEL', fromCity: 'Delhi', to: 'RUH', toCity: 'Riyadh', type: 'international', cabinClass: 'Economy', passengers: { adults: 1 }, dateOffsetDays: 28, priority: 'HIGH', deepFocus: true },
  { id: 'INTL-PRIO-24', label: 'Priority | CCU→BKK | Bangkok', from: 'CCU', fromCity: 'Kolkata', to: 'BKK', toCity: 'Bangkok', type: 'international', cabinClass: 'Economy', passengers: { adults: 1 }, dateOffsetDays: 35, priority: 'HIGH', deepFocus: true },
  { id: 'INTL-PRIO-25', label: 'Priority | DEL→KTM | Kathmandu', from: 'DEL', fromCity: 'Delhi', to: 'KTM', toCity: 'Kathmandu', type: 'international', cabinClass: 'Economy', passengers: { adults: 1 }, dateOffsetDays: 45, priority: 'HIGH', deepFocus: true },
  { id: 'INTL-PRIO-26', label: 'Priority | HYD→DXB | Dubai', from: 'HYD', fromCity: 'Hyderabad', to: 'DXB', toCity: 'Dubai', type: 'international', cabinClass: 'Economy', passengers: { adults: 1 }, dateOffsetDays: 14, priority: 'HIGH', deepFocus: true },
  { id: 'INTL-PRIO-27', label: 'Priority | DEL→DOH | Doha', from: 'DEL', fromCity: 'Delhi', to: 'DOH', toCity: 'Doha', type: 'international', cabinClass: 'Economy', passengers: { adults: 1 }, dateOffsetDays: 21, priority: 'HIGH', deepFocus: true },
  { id: 'INTL-PRIO-28', label: 'Priority | HYD→KWI | Kuwait City', from: 'HYD', fromCity: 'Hyderabad', to: 'KWI', toCity: 'Kuwait City', type: 'international', cabinClass: 'Economy', passengers: { adults: 1 }, dateOffsetDays: 28, priority: 'HIGH', deepFocus: true },
  { id: 'INTL-PRIO-29', label: 'Priority | BOM→DPS | Bali', from: 'BOM', fromCity: 'Mumbai', to: 'DPS', toCity: 'Bali', type: 'international', cabinClass: 'Economy', passengers: { adults: 1 }, dateOffsetDays: 35, priority: 'HIGH', deepFocus: true },
  { id: 'INTL-PRIO-30', label: 'Priority | LKO→SHJ | Sharjah', from: 'LKO', fromCity: 'Lucknow', to: 'SHJ', toCity: 'Sharjah', type: 'international', cabinClass: 'Economy', passengers: { adults: 1 }, dateOffsetDays: 45, priority: 'HIGH', deepFocus: true },
  { id: 'INTL-PRIO-31', label: 'Priority | BOM→SHJ | Sharjah', from: 'BOM', fromCity: 'Mumbai', to: 'SHJ', toCity: 'Sharjah', type: 'international', cabinClass: 'Economy', passengers: { adults: 1 }, dateOffsetDays: 14, priority: 'HIGH', deepFocus: true },
  { id: 'INTL-PRIO-32', label: 'Priority | VNS→SHJ | Sharjah', from: 'VNS', fromCity: 'Varanasi', to: 'SHJ', toCity: 'Sharjah', type: 'international', cabinClass: 'Economy', passengers: { adults: 1 }, dateOffsetDays: 21, priority: 'HIGH', deepFocus: true },
  { id: 'INTL-PRIO-33', label: 'Priority | CCU→AUH | Abu Dhabi', from: 'CCU', fromCity: 'Kolkata', to: 'AUH', toCity: 'Abu Dhabi', type: 'international', cabinClass: 'Economy', passengers: { adults: 1 }, dateOffsetDays: 28, priority: 'HIGH', deepFocus: true },
  { id: 'INTL-PRIO-34', label: 'Priority | BOM→HKT | Phuket', from: 'BOM', fromCity: 'Mumbai', to: 'HKT', toCity: 'Phuket', type: 'international', cabinClass: 'Economy', passengers: { adults: 1 }, dateOffsetDays: 35, priority: 'HIGH', deepFocus: true },
  { id: 'INTL-PRIO-35', label: 'Priority | DXB→AMD | Ahmedabad', from: 'DXB', fromCity: 'Dubai', to: 'AMD', toCity: 'Ahmedabad', type: 'international', cabinClass: 'Economy', passengers: { adults: 1 }, dateOffsetDays: 45, priority: 'HIGH', deepFocus: true },
  { id: 'INTL-PRIO-36', label: 'Priority | BLR→KWI | Kuwait City', from: 'BLR', fromCity: 'Bangalore', to: 'KWI', toCity: 'Kuwait City', type: 'international', cabinClass: 'Economy', passengers: { adults: 1 }, dateOffsetDays: 14, priority: 'HIGH', deepFocus: true },
  { id: 'INTL-PRIO-37', label: 'Priority | DEL→DPS | Bali', from: 'DEL', fromCity: 'Delhi', to: 'DPS', toCity: 'Bali', type: 'international', cabinClass: 'Economy', passengers: { adults: 1 }, dateOffsetDays: 21, priority: 'HIGH', deepFocus: true },
  { id: 'INTL-PRIO-38', label: 'Priority | ATQ→SHJ | Sharjah', from: 'ATQ', fromCity: 'Amritsar', to: 'SHJ', toCity: 'Sharjah', type: 'international', cabinClass: 'Economy', passengers: { adults: 1 }, dateOffsetDays: 28, priority: 'HIGH', deepFocus: true },
  { id: 'INTL-PRIO-39', label: 'Priority | DEL→FJR | Fujairah', from: 'DEL', fromCity: 'Delhi', to: 'FJR', toCity: 'Fujairah', type: 'international', cabinClass: 'Economy', passengers: { adults: 1 }, dateOffsetDays: 35, priority: 'HIGH', deepFocus: true },
  { id: 'INTL-PRIO-40', label: 'Priority | DEL→BOF | Bournemouth', from: 'DEL', fromCity: 'Delhi', to: 'BOF', toCity: 'Bournemouth', type: 'international', cabinClass: 'Economy', passengers: { adults: 1 }, dateOffsetDays: 45, priority: 'HIGH', deepFocus: true },
  { id: 'INTL-PRIO-41', label: 'Priority | ATQ→DXB | Dubai', from: 'ATQ', fromCity: 'Amritsar', to: 'DXB', toCity: 'Dubai', type: 'international', cabinClass: 'Economy', passengers: { adults: 1 }, dateOffsetDays: 14, priority: 'HIGH', deepFocus: true },
  { id: 'INTL-PRIO-42', label: 'Priority | DXB→CCU | Kolkata', from: 'DXB', fromCity: 'Dubai', to: 'CCU', toCity: 'Kolkata', type: 'international', cabinClass: 'Economy', passengers: { adults: 1 }, dateOffsetDays: 21, priority: 'HIGH', deepFocus: true },
  { id: 'INTL-PRIO-43', label: 'Priority | BKK→CCU | Kolkata', from: 'BKK', fromCity: 'Bangkok', to: 'CCU', toCity: 'Kolkata', type: 'international', cabinClass: 'Economy', passengers: { adults: 1 }, dateOffsetDays: 28, priority: 'HIGH', deepFocus: true },
  { id: 'INTL-PRIO-44', label: 'Priority | AMD→DPS | Bali', from: 'AMD', fromCity: 'Ahmedabad', to: 'DPS', toCity: 'Bali', type: 'international', cabinClass: 'Economy', passengers: { adults: 1 }, dateOffsetDays: 35, priority: 'HIGH', deepFocus: true },
  { id: 'INTL-PRIO-45', label: 'Priority | LKO→AUH | Abu Dhabi', from: 'LKO', fromCity: 'Lucknow', to: 'AUH', toCity: 'Abu Dhabi', type: 'international', cabinClass: 'Economy', passengers: { adults: 1 }, dateOffsetDays: 45, priority: 'HIGH', deepFocus: true },
  { id: 'INTL-PRIO-46', label: 'Priority | DAC→KUL | Kuala Lumpur', from: 'DAC', fromCity: 'Dhaka', to: 'KUL', toCity: 'Kuala Lumpur', type: 'international', cabinClass: 'Economy', passengers: { adults: 1 }, dateOffsetDays: 14, priority: 'HIGH', deepFocus: true },
  { id: 'INTL-PRIO-47', label: 'Priority | DEL→LHR | London', from: 'DEL', fromCity: 'Delhi', to: 'LHR', toCity: 'London', type: 'international', cabinClass: 'Economy', passengers: { adults: 1 }, dateOffsetDays: 21, priority: 'HIGH', deepFocus: true },
  { id: 'INTL-PRIO-48', label: 'Priority | BOM→SIN | Singapore', from: 'BOM', fromCity: 'Mumbai', to: 'SIN', toCity: 'Singapore', type: 'international', cabinClass: 'Economy', passengers: { adults: 1 }, dateOffsetDays: 28, priority: 'HIGH', deepFocus: true },
  { id: 'INTL-PRIO-49', label: 'Priority | LAX→AMD | Ahmedabad', from: 'LAX', fromCity: 'Los Angeles', to: 'AMD', toCity: 'Ahmedabad', type: 'international', cabinClass: 'Economy', passengers: { adults: 1 }, dateOffsetDays: 35, priority: 'HIGH', deepFocus: true },
  { id: 'INTL-PRIO-50', label: 'Priority | DEL→HKT | Phuket', from: 'DEL', fromCity: 'Delhi', to: 'HKT', toCity: 'Phuket', type: 'international', cabinClass: 'Economy', passengers: { adults: 1 }, dateOffsetDays: 45, priority: 'HIGH', deepFocus: true },
];

const INTL_PRIORITY_PICK_RATE = 0.75; // 75% of INTL picks come from priority list

module.exports = { INTERNATIONAL_DEEP_SCENARIOS, INTERNATIONAL_WEIGHT_BOOST, INTL_PRIORITY_SECTORS, INTL_PRIORITY_PICK_RATE };
