// Daily CLAUDE.md updater — writes the full EQIS project context to CLAUDE.md
// every 24 hours so Claude Code sessions always have the latest system state.
//
// Scheduled via node-cron in eqis.js: runs once daily at midnight IST.

const fs = require('fs');
const path = require('path');
const logger = require('../../utils/logger');
const { buildProjectTree } = require('./codeReader');
const { getActiveDirectives } = require('../ceoDirectives');

const CLAUDE_MD_PATH = path.join(__dirname, '..', '..', 'CLAUDE.md');

function getMetricsSummary() {
  try {
    const metricsPath = path.join(__dirname, '..', '..', 'state', 'metricsHistory.json');
    const metrics = JSON.parse(fs.readFileSync(metricsPath, 'utf-8'));
    const total = metrics.length;
    const last24h = metrics.filter(m => Date.now() - new Date(m.timestamp).getTime() < 24 * 60 * 60 * 1000);
    const byEngine = {};
    last24h.forEach(m => {
      const e = m.engineType || 'unknown';
      byEngine[e] = (byEngine[e] || 0) + 1;
    });
    return { totalAllTime: total, last24h: last24h.length, byEngine };
  } catch { return { totalAllTime: 0, last24h: 0, byEngine: {} }; }
}

function getSystemState() {
  try {
    const statePath = path.join(__dirname, '..', '..', 'state', 'systemState.json');
    return JSON.parse(fs.readFileSync(statePath, 'utf-8'));
  } catch { return {}; }
}

function getEngineState() {
  try {
    const statePath = path.join(__dirname, '..', '..', 'state', 'engineState.json');
    return JSON.parse(fs.readFileSync(statePath, 'utf-8'));
  } catch { return {}; }
}

function getIntervals() {
  try {
    const intPath = path.join(__dirname, '..', '..', 'state', 'intervals.json');
    return JSON.parse(fs.readFileSync(intPath, 'utf-8'));
  } catch { return {}; }
}

function getFrakaState() {
  try {
    const frakaPath = path.join(__dirname, '..', '..', 'state', 'fraka', 'frakaState.json');
    return JSON.parse(fs.readFileSync(frakaPath, 'utf-8'));
  } catch { return {}; }
}

function getBuildHistory() {
  try {
    const buildPath = path.join(__dirname, '..', '..', 'state', 'fraka', 'buildHistory.json');
    const builds = JSON.parse(fs.readFileSync(buildPath, 'utf-8'));
    return {
      total: builds.length,
      success: builds.filter(b => b.status === 'success').length,
      failed: builds.filter(b => b.status === 'failed' || b.status === 'failed-qa').length,
      lastBuild: builds.length > 0 ? builds[builds.length - 1] : null,
    };
  } catch { return { total: 0, success: 0, failed: 0, lastBuild: null }; }
}

function getEnvConfig() {
  // Read .env keys only (not values) for documentation
  try {
    const envPath = path.join(__dirname, '..', '..', '.env');
    const lines = fs.readFileSync(envPath, 'utf-8').split('\n');
    return lines
      .filter(l => l.includes('=') && !l.startsWith('#'))
      .map(l => l.split('=')[0].trim())
      .filter(Boolean);
  } catch { return []; }
}

function updateClaudeMd() {
  const now = new Date();
  const projectTree = buildProjectTree({ maxDepth: 3 });
  const metrics = getMetricsSummary();
  const systemState = getSystemState();
  const engineState = getEngineState();
  const intervals = getIntervals();
  const frakaState = getFrakaState();
  const directives = getActiveDirectives();
  const builds = getBuildHistory();
  const envKeys = getEnvConfig();

  const content = `# EQIS — ETRAV QA Intelligence System

> Auto-generated by FRAKA on ${now.toLocaleString('en-IN', { timeZone: 'Asia/Kolkata' })} IST
> This file is refreshed every 24 hours with the latest system context.

## What is EQIS?

EQIS is an autonomous QA testing system for Etrav Tech Ltd's B2B travel platform (new.etrav.in).
It runs 4 browser-automation engines via Playwright, evaluates every step with Claude AI,
and surfaces bugs, UX issues, and performance bottlenecks through a real-time Express dashboard.

FRAKA is the AI sub-CTO / full-stack developer / operations manager that oversees all of EQIS.

## Tech Stack

- **Runtime:** Node.js (CommonJS modules)
- **Browser automation:** Playwright + Chromium (headless)
- **AI evaluation:** Claude API (Haiku 4.5 for chat, Sonnet 4 for deep analysis)
- **Dashboard:** Express server on port ${intervals.dashboardPort || 4000}
- **Scheduling:** node-cron with pause/resume per engine
- **Persistence:** JSON files under state/ (no database)
- **Session monitoring:** Zipy (app.zipy.ai)

## Current Engine State

| Engine | Status | Interval | Last Run |
|--------|--------|----------|----------|
| Search Pulse | ${engineState.searchPulse?.status || '?'} | ${intervals.searchPulseMinutes || '?'} min | ${systemState.lastSearchPulseRun?.timestamp || 'never'} |
| Journey | ${engineState.journey?.status || '?'} | ${intervals.journeyMinutes || '?'} min | ${systemState.lastJourneyRun?.timestamp || 'never'} |
| Zipy | ${engineState.zipy?.status || '?'} | ${intervals.zipyMinutes || '?'} min | ${systemState.lastZipyRun?.timestamp || 'never'} |
| Full Booking | ${engineState.fullBooking?.status || '?'} | ${intervals.fullBookingMinutes || '?'} min | ${systemState.lastFullBookingRun?.timestamp || 'never'} |

## FRAKA Status

- **Active:** ${frakaState.active === true ? 'Yes (awake)' : 'No (sleeping)'}
- **Last review:** ${frakaState.lastReviewAt || 'never'}
- **Total reviews:** ${frakaState.totalReviews || 0}
- **Critical alerts:** ${(frakaState.criticalAlerts || []).length > 0 ? (frakaState.criticalAlerts || []).join('; ') : 'None'}

## CEO Directives (${directives.length} active)

${directives.length > 0 ? directives.map((d, i) => `${i + 1}. [${d.priority.toUpperCase()}][${d.category}] ${d.directive}`).join('\n') : 'No active directives.'}

## Build History

- **Total builds:** ${builds.total}
- **Successful:** ${builds.success}
- **Failed:** ${builds.failed}
- **Success rate:** ${builds.total > 0 ? Math.round((builds.success / builds.total) * 100) : 0}%
${builds.lastBuild ? `- **Last build:** ${builds.lastBuild.id} (${builds.lastBuild.status}) — ${(builds.lastBuild.task || '').slice(0, 100)}` : ''}

## Metrics Summary

- **All-time entries:** ${metrics.totalAllTime}
- **Last 24h:** ${metrics.last24h} runs
- **By engine (24h):** ${Object.entries(metrics.byEngine).map(([k, v]) => k + ': ' + v).join(', ') || 'none'}

## Environment Variables (keys only)

${envKeys.map(k => '- `' + k + '`').join('\n') || 'None found'}

## Project Structure

\`\`\`
${projectTree}
\`\`\`

## Key Files

| File | Purpose |
|------|---------|
| \`eqis.js\` | Main entry — CLI, startup, engine runners |
| \`fraka/agent.js\` | FRAKA chat handler (Haiku) — parses BUILD/DIRECTIVE/PROPOSALS |
| \`fraka/reviewer.js\` | Hourly deep review (Sonnet) |
| \`fraka/coder.js\` | Autonomous build pipeline (plan → write → QA → rollback) |
| \`fraka/systemPrompt.js\` | FRAKA persona, rules, proposal schema |
| \`fraka/ceoDirectives.js\` | Persistent CEO standing orders |
| \`fraka/tools/codeReader.js\` | Safe file read/write with path guards + blocklist |
| \`fraka/tools/codeQA.js\` | Active QA (syntax, require, credentials scan) |
| \`fraka/zipyKnowledge.js\` | Zipy domain knowledge for FRAKA |
| \`utils/cronManager.js\` | Engine scheduling, pause/resume, intervals |
| \`utils/tokenOptimizer.js\` | Claude API wrapper (FAST/STANDARD/DEEP modes) |
| \`dashboard/server.js\` | Express app — 30+ API routes |
| \`dashboard/api/frakaApi.js\` | FRAKA endpoints (chat, proposals, build, directives) |
| \`dashboard/api/otpApi.js\` | OTP management for Zipy/Etrav logins |
| \`dashboard/ui/index.html\` | Single-page dashboard (all tabs) |

## API Surface (key endpoints)

- \`GET /api/status\` — system health
- \`GET /api/fraka/status\` — FRAKA state + budget + wake/sleep
- \`POST /api/fraka/chat\` — send message to FRAKA {role, message, replyTo}
- \`POST /api/fraka/build\` — trigger autonomous code build {task}
- \`GET /api/fraka/performance\` — FRAKA activity stats
- \`GET /api/fraka/directives\` — CEO standing orders
- \`POST /api/otp/submit\` — submit OTP for Zipy/Etrav login {service, code}
- \`POST /api/fraka/wake\` / \`POST /api/fraka/sleep\` — wake/sleep toggle

## Dashboard Tabs

Live | Performance | History | Zipy | Cost | Settings | About (General + Technical) | CEO | Tech

## Safety Rails

- Path blocklist: .env, .git, node_modules, state/fraka/*.json, reports/, logs/
- Auto-backup before every file write → state/fraka/code-backups/
- Active QA on every build (syntax, require, brace balance, credential scan)
- Auto-rollback if any QA check fails
- $50/day budget cap with 80% warning + 100% pause proposal
- Credentials never exposed in chat

---
*Last updated: ${now.toISOString()}*
`;

  fs.writeFileSync(CLAUDE_MD_PATH, content, 'utf-8');
  logger.info('[FRAKA] CLAUDE.md updated (' + content.length + ' bytes)');
  return { path: CLAUDE_MD_PATH, bytes: content.length };
}

module.exports = { updateClaudeMd };
