/**
 * emailTemplates.js — HTML email templates for EQIS daily digests.
 *
 * Three audiences, three templates:
 *   - Tech team        → SearchPulse SPF digest (last 24h)
 *   - Marketing team   → ECD "Promote" hotels (Eagle Crest cheaper than market)
 *   - Contracting team → ECD "Renegotiate" hotels (market cheaper — talk to hotelier)
 *
 * Each template returns { subject, html, summaryLine, recordCount }. The
 * summaryLine is what we write to emailHistory.json for the dashboard view.
 *
 * Design goals:
 *   - Inline CSS only (gmail strips <style>, no class selectors)
 *   - Width 600px, mobile-friendly (Etrav teams read on phones)
 *   - One actionable list per email, no fluff
 *   - "Generated by EQIS · run-id · timestamp" footer for traceability
 */

const ESC_MAP = { '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' };
function esc(s) {
  if (s == null) return '';
  return String(s).replace(/[&<>"']/g, (c) => ESC_MAP[c]);
}
function fmtINR(n) {
  if (n == null || !isFinite(n)) return '—';
  return '₹' + Math.round(n).toLocaleString('en-IN');
}
function fmtPct(n) {
  if (n == null || !isFinite(n)) return '—';
  const s = (n > 0 ? '+' : '') + n.toFixed(1) + '%';
  return s;
}
function fmtDate(iso) {
  if (!iso) return '';
  try {
    const d = new Date(iso);
    return d.toLocaleString('en-IN', { timeZone: 'Asia/Kolkata', hour: '2-digit', minute: '2-digit', day: '2-digit', month: 'short' });
  } catch { return ''; }
}
function nights(checkin, checkout) {
  if (!checkin || !checkout) return 1;
  try {
    const ms = new Date(checkout) - new Date(checkin);
    if (!isFinite(ms) || ms <= 0) return 1;
    return Math.max(1, Math.round(ms / 86400000));
  } catch { return 1; }
}

function wrap({ title, preheader, bodyHtml, footerHtml }) {
  // Outer table for max email-client compatibility (Outlook etc.)
  return [
    '<!DOCTYPE html><html><head>',
    '<meta charset="UTF-8">',
    '<meta name="viewport" content="width=device-width, initial-scale=1">',
    '<title>' + esc(title) + '</title>',
    '</head><body style="margin:0;padding:0;background:#f4f5f7;font-family:-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,sans-serif;color:#1a1a1a;">',
    '<div style="display:none;font-size:1px;color:#f4f5f7;line-height:1px;max-height:0;max-width:0;opacity:0;overflow:hidden;">' + esc(preheader) + '</div>',
    '<table width="100%" cellpadding="0" cellspacing="0" style="background:#f4f5f7;padding:24px 0;">',
    '<tr><td align="center">',
    // 2026-06-11: widened 600 → 800px so per-engine table + pie chart grid
    // breathe properly. Modern Gmail/Apple/Outlook-web render up to 900px
    // comfortably; mobile clients auto-scale-down regardless.
    '<table width="800" cellpadding="0" cellspacing="0" style="background:#fff;border-radius:8px;overflow:hidden;box-shadow:0 1px 3px rgba(0,0,0,.08);max-width:100%;">',
    '<tr><td style="padding:28px 40px 0;">',
    '<div style="font-size:11px;font-weight:700;color:#7a5400;letter-spacing:.08em;text-transform:uppercase;margin-bottom:4px;">EQIS Daily Digest</div>',
    '<h1 style="margin:0 0 4px;font-size:22px;line-height:1.25;color:#0a0a0a;">' + esc(title) + '</h1>',
    '<div style="font-size:13px;color:#666;">' + esc(preheader) + '</div>',
    '</td></tr>',
    '<tr><td style="padding:24px 40px 28px;">' + bodyHtml + '</td></tr>',
    '<tr><td style="padding:0 40px 28px;border-top:1px solid #eee;">',
    '<div style="padding-top:14px;font-size:11px;color:#888;line-height:1.5;">' + footerHtml + '</div>',
    '</td></tr>',
    '</table>',
    '</td></tr></table>',
    '</body></html>',
  ].join('');
}

function footer(runId) {
  const stamp = fmtDate(new Date().toISOString()) + ' IST';
  return 'Generated automatically by EQIS · ' + stamp
    + (runId ? ' · run ' + esc(runId) : '')
    + '<br>You\'re receiving this because you\'re on the EQIS notification roster. To change subscriptions, edit the Notifications tab on the EQIS dashboard.';
}

/* ────────────────────────────────────────────────────────────────────── *
 *  TECH TEAM — SearchPulse v2 daily performance digest
 *
 *  Three sections (per CEO agenda 2026-06-11):
 *    1. Per-engine performance breakdown — how each sub-engine
 *       (flight-dom / flight-intl / hotel-dom / hotel-intl) performed
 *    2. Failure cases with reproduce URLs — engineer can click + retry
 *    3. Daily performance metrics — SLA compliance, trend vs yesterday,
 *       slowest 5 searches so the team can drive everything under the
 *       "perfect timeline" SLA targets
 * ────────────────────────────────────────────────────────────────────── */

function _fmtDuration(ms) {
  if (!ms || !isFinite(ms)) return '\u2014';
  return (ms / 1000).toFixed(1) + 's';
}
function _fmtTimeOnly(iso) {
  if (!iso) return '';
  try {
    const d = new Date(iso);
    return d.toLocaleString('en-IN', { timeZone: 'Asia/Kolkata', hour: '2-digit', minute: '2-digit', day: '2-digit', month: 'short' });
  } catch { return ''; }
}

// 2026-06-11: per-engine doughnut chart via QuickChart.io. Returns a GET URL
// that renders a PNG — works in every email client (Gmail/Outlook/Apple/etc).
// 3 segments: Success (green) / Etrav issues (red) / EQIS bugs (gray).
function _pieChartUrl(engine) {
  // 2026-06-12: 4-slice quality split per engine:
  //   Perfect = success && duration <= 70% of SLA  (deep green)
  //   Median  = success && duration <= SLA         (light green)
  //   Delay   = success && duration >  SLA         (amber)
  //   Failure = Etrav-side issue                   (red)
  // EQIS automation bugs are FRAKA's internal problem and not shown.
  const perfect = engine.qPerfect || 0;
  const median  = engine.qMedian  || 0;
  const delay   = engine.qDelay   || 0;
  const failure = engine.qFailure || 0;
  const total = perfect + median + delay + failure || 1;
  const pct = (n) => Math.round((n / total) * 100) + '%';
  const config = {
    type: 'doughnut',
    data: {
      labels: [
        'Perfect ' + pct(perfect),
        'Median '  + pct(median),
        'Delay '   + pct(delay),
        'Failure ' + pct(failure),
      ],
      datasets: [{
        data: [perfect, median, delay, failure],
        backgroundColor: ['#0a7f3f', '#5fb878', '#e07b00', '#a40000'],
        borderColor: '#fff', borderWidth: 2,
      }],
    },
    options: {
      cutout: '55%',
      plugins: {
        title: { display: true, text: engine.name + ' \u2014 ' + (perfect + median + delay + failure) + ' searches', font: { size: 13, weight: 'bold' }, color: '#0a0a0a' },
        legend: { position: 'bottom', labels: { font: { size: 11, weight: 'bold' }, boxWidth: 12, padding: 10 } },
        datalabels: { display: false },
      },
    },
  };
  return 'https://quickchart.io/chart?w=340&h=340&bkg=white&c=' + encodeURIComponent(JSON.stringify(config));
}

/**
 * @param {Object} input
 * @param {Array}  input.engines           per-engine roll-up rows
 * @param {Array}  input.failures          failure cases with reproduce URLs
 * @param {Array}  input.slowest5          top 5 slowest searches today
 * @param {Object} input.totals            cross-engine totals
 * @param {number} input.overallSuccessRate
 * @param {number} input.spfRate
 * @param {string} input.runId             optional EQIS session id
 */
function renderTechDigest(input) {
  const engines     = Array.isArray(input.engines)  ? input.engines  : [];
  const failures    = Array.isArray(input.failures) ? input.failures : [];
  const slowest5    = Array.isArray(input.slowest5) ? input.slowest5 : [];
  const totals      = input.totals || { totalSearches: 0, totalSuccess: 0, totalSpf: 0 };
  const successRate = input.overallSuccessRate != null ? input.overallSuccessRate : (totals.totalSearches ? (totals.totalSuccess / totals.totalSearches) * 100 : 0);
  const spfRate     = input.spfRate != null ? input.spfRate : (totals.totalSearches ? ((totals.totalEtravIssues || 0) / totals.totalSearches) * 100 : 0);

  // ── Hero status ──────────────────────────────────────────────────
  const heroColor = (totals.totalEtravIssues || 0) > 5 ? '#a40000' : (totals.totalEtravIssues || 0) > 0 ? '#7a5400' : '#0a7f3f';
  const heroLabel = (totals.totalEtravIssues || 0) > 5 ? 'CRITICAL' : (totals.totalEtravIssues || 0) > 0 ? 'DEGRADED' : 'HEALTHY';

  // ── Section 1: per-engine performance ────────────────────────────
  const engineRows = engines.map(e => {
    const slaColor = e.slaCompliancePct >= 90 ? '#0a7f3f' : e.slaCompliancePct >= 70 ? '#7a5400' : '#a40000';
    const trendIcon = e.trend === 'improving' ? '\u2193' : e.trend === 'degrading' ? '\u2191' : '\u2192';
    const trendColor = e.trend === 'improving' ? '#0a7f3f' : e.trend === 'degrading' ? '#a40000' : '#888';
    const trendLabel = e.yesterdayAvgMs ? trendIcon + ' vs ' + _fmtDuration(e.yesterdayAvgMs) + ' yest' : '';
    // Use etravIssues for the "issues" column so EQIS automation bugs don't
    // mislead the tech team into thinking Etrav has problems they need to fix.
    const etravIssues = e.etravIssues || 0;
    const successColor = etravIssues > 0 ? '#a40000' : '#0a7f3f';
    return '<tr>'
      + '<td style="padding:10px 12px;font-size:13px;border-bottom:1px solid #eee;font-weight:600;">' + esc(e.name) + '</td>'
      + '<td style="padding:10px 12px;font-size:13px;text-align:right;border-bottom:1px solid #eee;font-variant-numeric:tabular-nums;">' + e.total + '</td>'
      + '<td style="padding:10px 12px;font-size:13px;text-align:right;border-bottom:1px solid #eee;font-variant-numeric:tabular-nums;color:' + successColor + ';font-weight:600;">' + e.success + '/' + e.total + '<br><span style="font-size:10px;font-weight:400;">(' + e.successRate.toFixed(0) + '%)</span></td>'
      + '<td style="padding:10px 12px;font-size:13px;text-align:right;border-bottom:1px solid #eee;font-variant-numeric:tabular-nums;color:' + (etravIssues > 0 ? '#a40000' : '#666') + ';font-weight:' + (etravIssues > 0 ? '700' : '400') + ';">' + etravIssues + '</td>'
      // 2026-06-11: collapsed Avg + P95 into one cell, dropped P95 column.
      // Cell now reads as e.g. "12.2s avg" with "13.2s P95" subtitle.
      + '<td style="padding:10px 12px;font-size:13px;text-align:right;border-bottom:1px solid #eee;font-variant-numeric:tabular-nums;">'
      +   _fmtDuration(e.avgDurationMs) + ' <span style="font-size:9px;color:#888;text-transform:uppercase;letter-spacing:.04em;">avg</span>'
      +   '<br><span style="font-size:10px;color:#888;">P95 ' + _fmtDuration(e.p95DurationMs) + '</span>'
      +   (trendLabel ? '<br><span style="font-size:10px;color:' + trendColor + ';">' + trendLabel + '</span>' : '')
      + '</td>'
      + '<td style="padding:10px 12px;font-size:13px;text-align:right;border-bottom:1px solid #eee;font-variant-numeric:tabular-nums;color:#888;">' + _fmtDuration(e.slaMs) + '</td>'
      + '<td style="padding:10px 12px;font-size:13px;text-align:right;border-bottom:1px solid #eee;font-variant-numeric:tabular-nums;color:' + slaColor + ';font-weight:700;">' + e.slaCompliancePct.toFixed(0) + '%</td>'
      + '</tr>';
  }).join('');

  // ── Section 2: failure cases with reproduce URLs ─────────────────
  const failureRows = failures.map(f => {
    return '<tr>'
      + '<td style="padding:10px 12px;font-size:11px;border-bottom:1px solid #eee;vertical-align:top;color:#666;white-space:nowrap;">'
      +   esc(_fmtTimeOnly(f.timestamp))
      +   '<br><span style="font-weight:600;color:#333;font-size:12px;">' + esc(f.engine || '') + '</span>'
      + '</td>'
      + '<td style="padding:10px 12px;font-size:12px;border-bottom:1px solid #eee;vertical-align:top;">'
      +   '<div style="font-weight:600;">' + esc(f.route || '\u2014') + '</div>'
      +   '<div style="color:#a40000;font-size:11px;margin-top:2px;">' + esc(f.errorClass || 'UNKNOWN') + '</div>'
      +   (f.error ? '<div style="color:#444;font-size:11px;margin-top:4px;font-family:Monaco,Menlo,monospace;line-height:1.4;">' + esc(String(f.error).slice(0, 140)) + '</div>' : '')
      + '</td>'
      + '<td style="padding:10px 12px;font-size:11px;border-bottom:1px solid #eee;vertical-align:top;">'
      +   '<a href="' + esc(f.reproduceUrl || '') + '" style="color:#2563eb;text-decoration:underline;font-weight:600;font-size:11px;font-family:Monaco,Menlo,monospace;word-break:break-all;line-height:1.4;">' + esc(f.reproduceUrl || '\u2014') + '</a>'
      +   (f.screenshot ? '<div style="color:#888;font-size:10px;font-family:Monaco,Menlo,monospace;margin-top:6px;word-break:break-all;">' + esc(String(f.screenshot).split('/').slice(-2).join('/')) + '</div>' : '')
      + '</td>'
      + '</tr>';
  }).join('');

  // ── Section 3: slowest search PER engine ─────────────────────────
  // Shows the slowest single search from each engine instead of top 5 overall —
  // more informative because one slow engine no longer dominates the table.
  const slowestRows = slowest5.map((s) => {
    const overSla = (s.slaMs && s.duration > s.slaMs);
    const color = overSla ? '#a40000' : '#0a7f3f';
    const note  = overSla ? '<span style="font-size:10px;font-weight:400;color:' + color + ';"> (over ' + _fmtDuration(s.slaMs) + ' SLA)</span>' : '';
    return '<tr>'
      + '<td style="padding:8px 12px;font-size:12px;border-bottom:1px solid #eee;font-weight:600;">' + esc(s.engine || '') + '</td>'
      + '<td style="padding:8px 12px;font-size:13px;text-align:right;border-bottom:1px solid #eee;font-variant-numeric:tabular-nums;font-weight:700;color:' + color + ';">' + _fmtDuration(s.duration) + note + '</td>'
      + '</tr>';
  }).join('');

  // ── Assemble body ────────────────────────────────────────────────
  const body = [
    // Hero
    '<div style="background:#fff;border:1px solid #eee;border-radius:6px;padding:16px;margin-bottom:18px;">',
    '<div style="display:inline-block;padding:2px 8px;font-size:11px;font-weight:700;color:#fff;background:' + heroColor + ';border-radius:4px;letter-spacing:.05em;">' + heroLabel + '</div>',
    // 2026-06-11: Outlook-compat — replaced display:flex with a 3-cell table.
    // Outlook (Word renderer) strips flex; this lays out as columns everywhere.
    '<table cellpadding="0" cellspacing="0" border="0" style="margin-top:12px;width:100%;">',
    '<tr>',
    '<td style="padding-right:24px;vertical-align:bottom;width:33%;">',
    '<div style="font-size:28px;font-weight:700;color:' + heroColor + ';font-variant-numeric:tabular-nums;line-height:1;">' + (totals.totalEtravIssues || 0) + '</div>',
    '<div style="font-size:11px;color:#666;text-transform:uppercase;letter-spacing:.05em;font-weight:600;margin-top:4px;">Etrav issue' + ((totals.totalEtravIssues || 0) === 1 ? '' : 's') + ' yesterday</div>',
    '</td>',
    '<td style="padding-right:24px;vertical-align:bottom;width:33%;">',
    '<div style="font-size:28px;font-weight:700;color:#0a0a0a;font-variant-numeric:tabular-nums;line-height:1;">' + totals.totalSearches + '</div>',
    '<div style="font-size:11px;color:#666;text-transform:uppercase;letter-spacing:.05em;font-weight:600;margin-top:4px;">Total searches</div>',
    '</td>',
    '<td style="vertical-align:bottom;width:34%;">',
    '<div style="font-size:28px;font-weight:700;color:' + (successRate >= 95 ? '#0a7f3f' : successRate >= 80 ? '#7a5400' : '#a40000') + ';font-variant-numeric:tabular-nums;line-height:1;">' + successRate.toFixed(1) + '%</div>',
    '<div style="font-size:11px;color:#666;text-transform:uppercase;letter-spacing:.05em;font-weight:600;margin-top:4px;">Success rate</div>',
    '</td>',
    '</tr>',
    '</table>',
    '<div style="font-size:12px;color:#666;margin-top:14px;line-height:1.5;">Window: yesterday (00:00 to 23:59 IST). Trend comparisons use yesterday\'s same metric. Per-engine SLA targets define the &ldquo;perfect timeline&rdquo; you\'re working toward.</div>',
    '</div>',

    // Section 1: Per-engine performance
    '<h2 style="margin:24px 0 10px;font-size:16px;color:#0a0a0a;">\u2699 Per-engine performance</h2>',
    '<div style="font-size:12px;color:#666;margin-bottom:10px;">How each SearchPulse sub-engine performed today. SLA = the target duration the team is steering toward. Compliance = % of successful searches that finished under SLA.</div>',
    '<table width="100%" cellpadding="0" cellspacing="0" style="border-collapse:collapse;border:1px solid #eee;border-radius:6px;overflow:hidden;margin-bottom:24px;">',
    '<thead><tr style="background:#fafafa;">',
    '<th style="padding:10px 12px;text-align:left;font-size:11px;color:#666;font-weight:600;text-transform:uppercase;letter-spacing:.05em;">Engine</th>',
    '<th style="padding:10px 12px;text-align:right;font-size:11px;color:#666;font-weight:600;text-transform:uppercase;letter-spacing:.05em;">Total</th>',
    '<th style="padding:10px 12px;text-align:right;font-size:11px;color:#666;font-weight:600;text-transform:uppercase;letter-spacing:.05em;">Success</th>',
    '<th style="padding:10px 12px;text-align:right;font-size:11px;color:#666;font-weight:600;text-transform:uppercase;letter-spacing:.05em;">Etrav issues</th>',
    '<th style="padding:10px 12px;text-align:right;font-size:11px;color:#666;font-weight:600;text-transform:uppercase;letter-spacing:.05em;">Avg / P95</th>',
    '<th style="padding:10px 12px;text-align:right;font-size:11px;color:#666;font-weight:600;text-transform:uppercase;letter-spacing:.05em;">SLA target</th>',
    '<th style="padding:10px 12px;text-align:right;font-size:11px;color:#666;font-weight:600;text-transform:uppercase;letter-spacing:.05em;">SLA met</th>',
    '</tr></thead>',
    '<tbody>' + engineRows + '</tbody></table>',

    // Section 2: Per-engine pie charts (Success / Etrav issues / EQIS bugs)
    '<h2 style="margin:24px 0 10px;font-size:16px;color:#0a0a0a;">\u{1F4CA} Search quality split &middot; per engine</h2>',
    '<div style="font-size:12px;color:#666;margin-bottom:10px;">Each chart splits today\'s searches by quality. <strong style="color:#0a7f3f;">Perfect</strong> = under 70% of SLA. <strong style="color:#5fb878;">Median</strong> = within SLA. <strong style="color:#e07b00;">Delay</strong> = success but slower than SLA. <strong style="color:#a40000;">Failure</strong> = Etrav-side issue.</div>',
    '<table width="100%" cellpadding="0" cellspacing="0" style="margin-bottom:24px;border-collapse:separate;">',
    '<tr>',
    '<td width="50%" align="center" style="padding:6px;"><img src="' + esc(engines[0] ? _pieChartUrl(engines[0]) : '') + '" width="340" height="340" alt="Flight Domestic split" style="max-width:100%;height:auto;display:block;border:0;margin:0 auto;"><div style="margin-top:6px;font-size:13px;font-weight:700;color:#0a0a0a;text-align:center;">' + esc(engines[0] ? engines[0].name : 'Flight Domestic') + '</div><div style="font-size:11px;color:#666;text-align:center;margin-top:2px;">' + (engines[0] ? (engines[0].total + ' search' + (engines[0].total === 1 ? '' : 'es')) : '') + '</div></td>',
    '<td width="50%" align="center" style="padding:6px;"><img src="' + esc(engines[1] ? _pieChartUrl(engines[1]) : '') + '" width="340" height="340" alt="Flight International split" style="max-width:100%;height:auto;display:block;border:0;margin:0 auto;"><div style="margin-top:6px;font-size:13px;font-weight:700;color:#0a0a0a;text-align:center;">' + esc(engines[1] ? engines[1].name : 'Flight International') + '</div><div style="font-size:11px;color:#666;text-align:center;margin-top:2px;">' + (engines[1] ? (engines[1].total + ' search' + (engines[1].total === 1 ? '' : 'es')) : '') + '</div></td>',
    '</tr>',
    '<tr>',
    '<td width="50%" align="center" style="padding:6px;"><img src="' + esc(engines[2] ? _pieChartUrl(engines[2]) : '') + '" width="340" height="340" alt="Hotel Domestic split" style="max-width:100%;height:auto;display:block;border:0;margin:0 auto;"><div style="margin-top:6px;font-size:13px;font-weight:700;color:#0a0a0a;text-align:center;">' + esc(engines[2] ? engines[2].name : 'Hotel Domestic') + '</div><div style="font-size:11px;color:#666;text-align:center;margin-top:2px;">' + (engines[2] ? (engines[2].total + ' search' + (engines[2].total === 1 ? '' : 'es')) : '') + '</div></td>',
    '<td width="50%" align="center" style="padding:6px;"><img src="' + esc(engines[3] ? _pieChartUrl(engines[3]) : '') + '" width="340" height="340" alt="Hotel International split" style="max-width:100%;height:auto;display:block;border:0;margin:0 auto;"><div style="margin-top:6px;font-size:13px;font-weight:700;color:#0a0a0a;text-align:center;">' + esc(engines[3] ? engines[3].name : 'Hotel International') + '</div><div style="font-size:11px;color:#666;text-align:center;margin-top:2px;">' + (engines[3] ? (engines[3].total + ' search' + (engines[3].total === 1 ? '' : 'es')) : '') + '</div></td>',
    '</tr>',
    '</table>',

    // Section 3: Etrav-side failures only (EQIS bugs filtered out per CEO directive 2026-06-11)
    '<h2 style="margin:24px 0 10px;font-size:16px;color:#0a0a0a;">\u26A0 Etrav-side issues &middot; needs investigation</h2>',
    failures.length === 0
      ? '<div style="padding:16px;text-align:center;color:#0a7f3f;font-weight:600;border:1px dashed #c8e7d3;border-radius:6px;margin-bottom:24px;">\u2713 No failures today. All engines clean.</div>'
      : '<div style="font-size:12px;color:#666;margin-bottom:10px;">Each row links to an Etrav URL the engineer can paste in their browser to reproduce the exact route and surface the same failure.</div>'
        + '<table width="100%" cellpadding="0" cellspacing="0" style="border-collapse:collapse;border:1px solid #eee;border-radius:6px;overflow:hidden;margin-bottom:24px;">'
        + '<thead><tr style="background:#fafafa;">'
        +   '<th style="padding:10px 12px;text-align:left;font-size:11px;color:#666;font-weight:600;text-transform:uppercase;letter-spacing:.05em;">When &amp; engine</th>'
        +   '<th style="padding:10px 12px;text-align:left;font-size:11px;color:#666;font-weight:600;text-transform:uppercase;letter-spacing:.05em;">Route &amp; error</th>'
        +   '<th style="padding:10px 12px;text-align:left;font-size:11px;color:#666;font-weight:600;text-transform:uppercase;letter-spacing:.05em;">Failure URL</th>'
        + '</tr></thead>'
        + '<tbody>' + failureRows + '</tbody></table>',

    // Section 3: Performance trend & slowest per engine
    '<h2 style="margin:24px 0 10px;font-size:16px;color:#0a0a0a;">\u23F1 Slowest search per engine (yesterday)</h2>',
    '<div style="font-size:12px;color:#666;margin-bottom:10px;">The longest single search from each engine yesterday. Red rows breach the &ldquo;perfect timeline&rdquo; SLA &mdash; those are the engines to optimize first.</div>',
    slowest5.length === 0
      ? '<div style="padding:16px;text-align:center;color:#888;border:1px dashed #ddd;border-radius:6px;">No search durations recorded yesterday.</div>'
      : '<table width="100%" cellpadding="0" cellspacing="0" style="border-collapse:collapse;border:1px solid #eee;border-radius:6px;overflow:hidden;">'
        + '<thead><tr style="background:#fafafa;">'
        +   '<th style="padding:10px 12px;text-align:left;font-size:11px;color:#666;font-weight:600;text-transform:uppercase;letter-spacing:.05em;">Engine</th>'
        +   '<th style="padding:10px 12px;text-align:right;font-size:11px;color:#666;font-weight:600;text-transform:uppercase;letter-spacing:.05em;">Slowest today</th>'
        + '</tr></thead>'
        + '<tbody>' + slowestRows + '</tbody></table>',
  ].join('');

  return {
    subject: 'EQIS \u00b7 SearchPulse daily report (yesterday) \u2014 '
      + ((totals.totalEtravIssues || 0) > 0 ? (totals.totalEtravIssues || 0) + ' Etrav issue' + ((totals.totalEtravIssues || 0) === 1 ? '' : 's') : 'all healthy')
      + ' \u00b7 ' + successRate.toFixed(0) + '% success on ' + totals.totalSearches + ' searches',
    html: wrap({
      title: 'SearchPulse \u2014 daily performance digest',
      preheader: totals.totalSearches + ' searches \u00b7 ' + successRate.toFixed(1) + '% success \u00b7 ' + (totals.totalEtravIssues || 0) + ' Etrav issues',
      bodyHtml: body,
      footerHtml: footer(input.runId),
    }),
    summaryLine: totals.totalSearches + ' searches \u00b7 ' + successRate.toFixed(1) + '% success \u00b7 ' + (totals.totalEtravIssues || 0) + ' Etrav issues',
    recordCount: (totals.totalEtravIssues || 0),
  };
}

/* ────────────────────────────────────────────────────────────────────── *
 *  MARKETING TEAM — ECD "Promote" digest (good pricing = ECD cheaper)
 * ────────────────────────────────────────────────────────────────────── */

function ecdHotelRowAction(row) {
  let ecdN = 0, normN = 0;
  for (const c of (row.combos || [])) {
    if (c.verdict === 'ECD_CHEAPER') ecdN++;
    else if (c.verdict === 'NORMAL_CHEAPER') normN++;
  }
  const c0 = (row.combos || [])[0] || null;
  const isPromote = ecdN > 0 && normN === 0;
  const isReneg   = normN >= ecdN && normN > 0;
  const c0v = c0 && c0.verdict;
  const c0Diff = c0 && c0.diff && typeof c0.diff.absINR === 'number' ? c0.diff.absINR : null;
  const c0Pct  = c0 && c0.diff && typeof c0.diff.pct === 'number'    ? c0.diff.pct    : null;
  const ecdT  = c0 && c0.ecd    && typeof c0.ecd.totalPrice    === 'number' ? c0.ecd.totalPrice    : null;
  const normT = c0 && c0.normal && typeof c0.normal.totalPrice === 'number' ? c0.normal.totalPrice : null;
  const N = nights(row.checkin, row.checkout);
  const R = Math.max(1, Number((row.pax && row.pax.rooms) || row.rooms || 1));
  const unit = Math.max(1, N * R);
  const savingINR = (c0v === 'ECD_CHEAPER' && c0Diff != null) ? Math.abs(c0Diff) : 0;
  const overpayINR = (c0v === 'NORMAL_CHEAPER' && c0Diff != null) ? Math.abs(c0Diff) : 0;
  return {
    isPromote, isReneg,
    ecdTotal: ecdT, normTotal: normT,
    ecdPerNight: ecdT != null ? Math.round(ecdT / unit) : null,
    normPerNight: normT != null ? Math.round(normT / unit) : null,
    savingTotal: savingINR, savingPerNight: Math.round(savingINR / unit),
    overpayTotal: overpayINR, overpayPerNight: Math.round(overpayINR / unit),
    pct: c0Pct != null ? Math.abs(c0Pct) : 0,
    nights: N, rooms: R,
    roomName: c0 ? c0.roomCategory : '',
    mealName: c0 ? c0.mealPlan : '',
  };
}

// 2026-06-12: per user request — both promote and renegotiate digests now
// cap at 3 hotels and show a room-by-room price-difference table inside
// each hotel card. This shared helper renders one hotel "card" with all of
// its matching combos. `mode` controls colour scheme + header label.
//
//   mode='promote'   → green; column header "You save"
//   mode='renegotiate' → red;   column header "You overpay"
function _ecdHotelCardHtml(hotel, matchingCombos, mode, index) {
  const colorAccent = mode === 'promote' ? '#0a7f3f' : '#a40000';
  const bgAccent    = mode === 'promote' ? '#e6f7ec' : '#fef2f2';
  const diffLabel   = mode === 'promote' ? 'You save'  : 'You overpay';
  const diffSign    = mode === 'promote' ? '-' : '+';

  const N = nights(hotel.checkin, hotel.checkout);
  const R = Math.max(1, Number((hotel.pax && hotel.pax.rooms) || hotel.rooms || 1));
  const unit = Math.max(1, N * R);

  let hotelTotalDiff = 0;
  const comboRows = matchingCombos.map((c) => {
    const ecdT  = c.ecd    && typeof c.ecd.totalPrice    === 'number' ? c.ecd.totalPrice    : null;
    const normT = c.normal && typeof c.normal.totalPrice === 'number' ? c.normal.totalPrice : null;
    const absINR = c.diff && typeof c.diff.absINR === 'number' ? Math.abs(c.diff.absINR) : 0;
    const pct    = c.diff && typeof c.diff.pct    === 'number' ? Math.abs(c.diff.pct)    : 0;
    hotelTotalDiff += absINR;
    const ecdPerNight  = ecdT  != null ? Math.round(ecdT  / unit) : null;
    const normPerNight = normT != null ? Math.round(normT / unit) : null;
    const diffPerNight = Math.round(absINR / unit);
    return '<tr>'
      + '<td style="padding:8px 12px;font-size:12px;border-bottom:1px solid #f0f0f0;vertical-align:top;">'
      +   '<div style="font-weight:600;">' + esc(c.roomCategory || 'Room category') + '</div>'
      +   (c.mealPlan ? '<div style="font-size:10px;color:#888;margin-top:1px;">' + esc(c.mealPlan) + '</div>' : '')
      + '</td>'
      + '<td style="padding:8px 12px;text-align:right;font-size:12px;border-bottom:1px solid #f0f0f0;vertical-align:top;font-variant-numeric:tabular-nums;">'
      +   '<div style="font-weight:600;">' + fmtINR(ecdPerNight) + '</div>'
      +   '<div style="font-size:10px;color:#888;">' + fmtINR(ecdT) + ' total</div>'
      + '</td>'
      + '<td style="padding:8px 12px;text-align:right;font-size:12px;border-bottom:1px solid #f0f0f0;vertical-align:top;font-variant-numeric:tabular-nums;color:#555;">'
      +   '<div>' + fmtINR(normPerNight) + '</div>'
      +   '<div style="font-size:10px;color:#888;">' + fmtINR(normT) + ' total</div>'
      + '</td>'
      + '<td style="padding:8px 12px;text-align:right;font-size:12px;border-bottom:1px solid #f0f0f0;vertical-align:top;font-variant-numeric:tabular-nums;color:' + colorAccent + ';">'
      +   '<div style="font-weight:700;">' + fmtINR(diffPerNight) + '</div>'
      +   '<div style="font-size:10px;">' + diffSign + pct.toFixed(1) + '% · ' + fmtINR(absINR) + ' total</div>'
      + '</td>'
      + '</tr>';
  }).join('');

  return '<div style="border:1px solid #eee;border-radius:8px;overflow:hidden;margin-bottom:14px;">'
    +   '<div style="padding:12px 16px;background:' + bgAccent + ';border-bottom:1px solid #eee;">'
    +     '<div style="display:inline-block;font-weight:700;font-size:11px;color:' + colorAccent + ';background:#fff;border:1px solid ' + colorAccent + '20;padding:1px 6px;border-radius:4px;margin-right:6px;">' + index + '</div>'
    +     '<span style="font-weight:700;font-size:14px;color:#0a0a0a;">' + esc(hotel.hotelName) + '</span>'
    +     '<div style="font-size:11px;color:#666;margin-top:3px;">' + esc(hotel.destination || '') + (hotel.city ? ' · ' + esc(hotel.city) : '') + (hotel.starRating ? ' · ' + hotel.starRating + '★' : '') + ' · ' + N + ' night' + (N > 1 ? 's' : '') + (R > 1 ? ' × ' + R + ' rooms' : '') + ' · ' + matchingCombos.length + ' room category' + (matchingCombos.length === 1 ? '' : 'ies') + ' to ' + (mode === 'promote' ? 'promote' : 'renegotiate') + '</div>'
    +   '</div>'
    +   '<table width="100%" cellpadding="0" cellspacing="0" style="border-collapse:collapse;">'
    +     '<thead><tr style="background:#fafafa;">'
    +       '<th style="padding:8px 12px;text-align:left;font-size:10px;color:#666;font-weight:600;text-transform:uppercase;letter-spacing:.05em;border-bottom:1px solid #eee;">Room + meal plan</th>'
    +       '<th style="padding:8px 12px;text-align:right;font-size:10px;color:#666;font-weight:600;text-transform:uppercase;letter-spacing:.05em;border-bottom:1px solid #eee;">Your rate /night</th>'
    +       '<th style="padding:8px 12px;text-align:right;font-size:10px;color:#666;font-weight:600;text-transform:uppercase;letter-spacing:.05em;border-bottom:1px solid #eee;">Market /night</th>'
    +       '<th style="padding:8px 12px;text-align:right;font-size:10px;color:#666;font-weight:600;text-transform:uppercase;letter-spacing:.05em;border-bottom:1px solid #eee;">' + diffLabel + ' /night</th>'
    +     '</tr></thead>'
    +     '<tbody>' + comboRows + '</tbody>'
    +   '</table>'
    + '</div>';
}

// 2026-06-12: hotels are now ranked + capped at 3 (per user). Each hotel
// expands to show every matching combo (room category + meal plan + rates).
const HOTEL_CARD_LIMIT = 3;

function renderMarketingDigest(input) {
  const hotels = Array.isArray(input.hotels) ? input.hotels : [];
  // 2026-06-12: per user — exactly ONE destination per day, exactly 3 hotels
  // from that destination. Rotation = least-recently-used destination wins;
  // within the chosen destination, prefer hotels not shown in the last 7 days.
  const rotation = require('./marketingRotation');
  const candidates = hotels.map(h => {
    const combos = (h.combos || []).filter(c => c.verdict === 'ECD_CHEAPER' && c.diff && typeof c.diff.absINR === 'number');
    if (combos.length === 0) return null;
    const totalSaving = combos.reduce((acc, c) => acc + Math.abs(c.diff.absINR), 0);
    return { hotelName: h.hotelName, destination: h.destination || 'Unknown', row: h, combos, totalSaving };
  }).filter(Boolean);
  const byDest = {};
  for (const c of candidates) {
    if (!byDest[c.destination]) byDest[c.destination] = [];
    byDest[c.destination].push(c);
  }
  for (const dest of Object.keys(byDest)) {
    byDest[dest].sort((a, b) => b.totalSaving - a.totalSaving);
  }
  const availableDestinations = Object.keys(byDest).filter(d => byDest[d].length > 0);
  const chosenDestination = rotation.pickDestinationForToday(availableDestinations);
  const HOTEL_LIMIT = 3;
  let picked = [];
  let destinationGroups = [];
  let totalSavings = 0;
  if (chosenDestination) {
    picked = rotation.pickFreshHotels(chosenDestination, byDest[chosenDestination], HOTEL_LIMIT);
    if (picked.length > 0) {
      destinationGroups = [{ destination: chosenDestination, items: picked }];
      rotation.recordSent(chosenDestination, picked.map(p => p.hotelName));
      rotation.recordDestinationSent(chosenDestination);
      picked.forEach(p => { totalSavings += p.totalSaving; });
    }
  }
  // 4. Render: a destination header + 3 hotel cards beneath each
  const destinationBlocks = destinationGroups.map(g => {
    const header = '<div style="margin:24px 0 10px;font-size:15px;font-weight:700;color:#0a0a0a;text-transform:uppercase;letter-spacing:.04em;border-bottom:2px solid #0a7f3f;padding-bottom:6px;">'
      + '\u{1F4CD} ' + esc(g.destination)
      + ' <span style="font-size:11px;font-weight:600;color:#0a7f3f;letter-spacing:0;text-transform:none;">'
      + g.items.length + ' hotel' + (g.items.length === 1 ? '' : 's') + ' to promote</span>'
      + '</div>';
    const cards = g.items.map((it, i) => _ecdHotelCardHtml(it.row, it.combos, 'promote', i + 1)).join('');
    return header + cards;
  }).join('');
  const totalHotels = picked.length;

  const body = [
    '<div style="background:#e6f7ec;border:1px solid #cce7d8;border-radius:6px;padding:16px;margin-bottom:18px;">',
    '<div style="font-size:11px;font-weight:700;color:#0a7f3f;letter-spacing:.05em;text-transform:uppercase;">Today\'s top wins</div>',
    '<div style="font-size:28px;font-weight:700;color:#0a7f3f;font-variant-numeric:tabular-nums;margin-top:4px;">' + totalHotels + ' hotel' + (totalHotels === 1 ? '' : 's') + '</div>',
    '<div style="font-size:13px;color:#0a5f2e;margin-top:2px;">' + (chosenDestination ? 'featured destination: ' + esc(chosenDestination) + ' \u2014 ' : '') + 'total potential ' + fmtINR(totalSavings) + ' in savings to highlight</div>',
    '</div>',
    totalHotels === 0
      ? '<div style="padding:16px;text-align:center;color:#7a5400;font-weight:600;border:1px dashed #f5cba7;border-radius:6px;">No promote opportunities in today\'s ECD cycle. Will retry tomorrow.</div>'
      : destinationBlocks
        + '<div style="margin-top:14px;font-size:12px;color:#666;line-height:1.5;">'
        + 'One featured destination per day with up to 3 hotels. Destinations rotate daily on a least-recently-used basis. '
        + 'Prices are per room per night, computed across all rooms \u00d7 nights in the requested booking window. '
        + 'Each card lists every room category where Eagle Crest beats the bedbank market.'
        + '</div>',
  ].join('');
  const promote = picked;

  return {
    subject: 'EQIS · Marketing — ' + promote.length + ' hotel' + (promote.length === 1 ? '' : 's') + ' to promote today',
    html: wrap({
      title: 'Hotels where Eagle Crest beats the market',
      preheader: promote.length + ' promotable hotel' + (promote.length === 1 ? '' : 's') + ' · ' + fmtINR(totalSavings) + ' total savings',
      bodyHtml: body,
      footerHtml: footer(input.runId),
    }),
    summaryLine: promote.length + ' promote · ' + fmtINR(totalSavings) + ' total savings',
    recordCount: promote.length,
  };
}

/* ────────────────────────────────────────────────────────────────────── *
 *  HOTEL CONTRACTING TEAM — ECD "Renegotiate" digest (market is cheaper)
 * ────────────────────────────────────────────────────────────────────── */

function renderContractingDigest(input) {
  const hotels = Array.isArray(input.hotels) ? input.hotels : [];
  // 2026-06-12: per user — Sudhir gets 5 hotels per day, ranked by largest
  // total overpay (top pricing difference). Hotels rotate daily so he sees
  // a fresh list each cycle to negotiate against.
  const rotation = require('./renegotiateRotation');
  const RENEG_HOTEL_LIMIT = 5;
  const ranked = hotels.map(h => {
    const combos = (h.combos || []).filter(c => c.verdict === 'NORMAL_CHEAPER' && c.diff && typeof c.diff.absINR === 'number');
    if (combos.length === 0) return null;
    const totalOverpay = combos.reduce((acc, c) => acc + Math.abs(c.diff.absINR), 0);
    return { hotelName: h.hotelName, row: h, combos, totalOverpay };
  }).filter(Boolean)
    .sort((a, b) => b.totalOverpay - a.totalOverpay);
  const reneg = rotation.pickFreshHotels(ranked, RENEG_HOTEL_LIMIT);
  if (reneg.length > 0) rotation.recordSent(reneg.map(r => r.hotelName));

  const rows = reneg.map((it, i) => _ecdHotelCardHtml(it.row, it.combos, 'renegotiate', i + 1)).join('');
  const totalOverpay = reneg.reduce((a, b) => a + b.totalOverpay, 0);

  const body = [
    '<div style="background:#fef2f2;border:1px solid #fac9c9;border-radius:6px;padding:16px;margin-bottom:18px;">',
    '<div style="font-size:11px;font-weight:700;color:#a40000;letter-spacing:.05em;text-transform:uppercase;">Today\'s renegotiation targets</div>',
    '<div style="font-size:28px;font-weight:700;color:#a40000;font-variant-numeric:tabular-nums;margin-top:4px;">' + reneg.length + ' hotel' + (reneg.length === 1 ? '' : 's') + '</div>',
    '<div style="font-size:13px;color:#7a1f1f;margin-top:2px;">where the bedbank market beats our direct rate — total gap ' + fmtINR(totalOverpay) + '</div>',
    '</div>',
    reneg.length === 0
      ? '<div style="padding:16px;text-align:center;color:#0a7f3f;font-weight:600;border:1px dashed #c8e7d3;border-radius:6px;">✓ Zero renegotiation targets today. ECD pricing is at or below market for every audited hotel.</div>'
      : rows
        + '<div style="margin-top:14px;padding:12px;background:#fffbeb;border:1px solid #f5e0a3;border-radius:6px;font-size:12px;color:#7a5400;line-height:1.5;">'
        + '<strong>Suggested hotelier message:</strong> "Hi team, our direct rate at <em>[hotel]</em> for [dates] / <em>[room category]</em> is ₹X per night, but the bedbank channel is selling the same room at ₹Y (+Z%). Can we revisit our direct allotment / rate to stay competitive?"'
        + '</div>'
        + '<div style="margin-top:10px;font-size:12px;color:#666;line-height:1.5;">'
        + 'Prices are per room per night, computed across all rooms × nights in the requested booking window. '
        + 'Each hotel card lists every room category where the bedbank market is beating our direct rate.'
        + '</div>',
  ].join('');

  return {
    subject: 'EQIS · Contracting — ' + reneg.length + ' hotel' + (reneg.length === 1 ? '' : 's') + ' to renegotiate today',
    html: wrap({
      title: 'Hotels to renegotiate — market is beating our direct rate',
      preheader: reneg.length + ' renegotiation target' + (reneg.length === 1 ? '' : 's') + ' · ' + fmtINR(totalOverpay) + ' total gap',
      bodyHtml: body,
      footerHtml: footer(input.runId),
    }),
    summaryLine: reneg.length + ' renegotiate · ' + fmtINR(totalOverpay) + ' total overpay',
    recordCount: reneg.length,
  };
}

module.exports = {
  renderTechDigest,
  renderMarketingDigest,
  renderContractingDigest,
  _internals: { ecdHotelRowAction, esc, fmtINR, nights },
};
